### ISSUE TITLE
Unable to download  anet_c3d.zip

### ISSUE THREAD

**Issue by IQraQasim10** [UARK-AICV/VLCAP#7]
Unable to download anet_c3d.zip. 
Is there any fix for downloading anet_c3d.zip smoothly? It shows network error after half of the download is complete

**Comment by Kashu7100** [comment]
Thank you for your interest. 
I just checked the downloading on my computer and could download the entire 14Gb zip file without a problem. 
Could you check your network environment and try again (maybe try a wired connection instead of wifi)?

I am happy to help you get our model set up, so if there is anything that I can help let me know.

**Comment by IQraQasim10** [comment]
Yes, changing to a wired connection with a handsome space in computer solved the issue. 
thanks for your support 🙌
